name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: "18" # or '20' depending on your React app

      # Install dependencies
      - run: npm install

      # Build React app (creates build/ folder)
      - run: npm run build

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NETFLIX_G_CLONE }}
          channelId: live
          projectId: netflix-g-clone
